import type { LucideIcon } from "lucide-react";
import {
  BellPlus,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  EllipsisVertical,
  Lock,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquareText,
  MessagesSquare,
  PenSquare,
  Plus,
  Search,
  Settings,
  ToggleLeft,
  ToggleRight,
  Trash2,
  UserPlus,
  X,
} from "lucide-react";

export const icons = {
  search: Search,
  edit: PenSquare,
  add: Plus,
  addAlert: BellPlus,
  settings: Settings,
  personAdd: UserPlus,
  arrowLeft: ChevronLeft,
  arrowRight: ChevronRight,
  announce: Megaphone,
  forum: MessagesSquare,
  menu: Menu,
  trash: Trash2,
  text: MessageSquareText,
  clear: X,
  arrowDown: ChevronDown,
  done: Check,
  lock: Lock,
  toggleOff: ToggleLeft,
  toggleOn: ToggleRight,
  message: MessageCircle,
  ellipsis: EllipsisVertical,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
